name: Run all book tests

on: 
  # Automatically run this action when a new push is made to repo
  push:
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  my-job:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out RVC3-MATLAB repository (for unit tests)
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."          

      - name: Start display server
        # Start a display server so Java Swing is available for testing
        run: |
          sudo apt-get install xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
          
      - name: Set up MATLAB
        # This uses the latest release of MATLAB. Can specify "release" if needed.
        # Use v2-beta for Java Swing access
        uses: matlab-actions/setup-matlab@v2-beta
        with:
          release: R2023b        

      - name: Print out ver details
        uses: matlab-actions/run-command@v1
        with:
          command: ver
        
      - name: Run MATLAB Tests
        # Only run tests in folder test/book
        uses: matlab-actions/run-tests@v1
        with:
          select-by-folder: test/book
          startup-options: -webfigures
          code-coverage-cobertura: code-coverage/coverage.xml
